# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57ea3cb7086bd259ad4c88bb829496cb6cacda9119b5f4bceb4832ab321223c192517a7705183a9c7e922f700e7b1836fc26f8c7ed12e79155118c9cbde57827

test:
  secret_key_base: 232eefa1d59f4b8e1526a79a7ccb7b89a3c05e9f1d693579836e622cd8e03c7bc96dc8d5e439821b3f8577d8a84bcaac88ec8c49197e863056d45ead15a59003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
